version: "3.6"
services:
    db:
      image: mysql:5
      container_name: db
      environment:
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_USER: admin
        MYSQL_DATABASE: HotelReviews
      volumes:
      - "./src/SQL/HotelReviewCreate.sql:/docker-entrypoint-initdb.d/1.sql"
#      - my-datavolume:/var/lib/mysql
      ports:
        - 3306:3306


    classifier:
      container_name: classifier
      build:
        context: ./src/Python/classifier
      depends_on: 
        - db
      ports:
        - 5001:5001
      restart: on-failure

    preprocessor:
      container_name: preprocessor
      build:
        context: ./src/Python/preprocessor
      depends_on: 
        - db
      ports:
        - 5002:5002
      restart: on-failure

    backend:
      container_name: backend
      build:
        context: ./src/Python/backend
      depends_on: 
        - db
      ports:
        - 5003:5003
      restart: on-failure

    frontend:
      container_name: frontend
      build: ./src/React
      ports:
        - 3000:3000

    nginx:
      image: nginx
      volumes:
        - "./default.conf:/etc/nginx/conf.d/default.conf"
      ports:
        - "8000:8000"
      command: [nginx-debug, "-g", "daemon off;"]

    apache_superset: 
      container_name: ApacheSuperset
      build:
        context: ./src/ApacheSuperset
      depends_on: 
        - db
      ports:
        - 8080:8088

      
      

volumes:
  my-datavolume:
