version: "3.6"
services:
    db:
      image: mysql
      container_name: db
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test_db
        
      ports:
        - 3307:3306

    backend:
      container_name: backend
      build:
        context: ./src/Python
      depends_on: 
        - db

      ports:
        - 5001:5001
      restart: on-failure

